### ISSUE TITLE
Android overflow:hidden can not change, how to solute it?

### ISSUE THREAD

**Issue by hufeng** [naoufal/react-native-accordion#12]

**Comment by naoufal** [comment]
Not sure I follow. Can you give a little more detail on what you're trying to achieve?

**Comment by naoufal** [comment]
@hufeng Closing issue.  Will reopen if you can provide more info.

**Comment by hufeng** [comment]
@naoufal thank you.

when this.setState({height: 0}} .

on Android, it still display. because React-Native android overflow default value is hidden

how to support on android?
