### ISSUE TITLE
[question] how to use with inverted scroll view

### ISSUE THREAD

**Issue by mvayngrib** [naoufal/react-native-accordion#15]
i have a component with an inverted scroll view and i'm using your accordion implementation there, but I find that because it's inverted, the accordion opens upwards instead of downwards, which is very unintuitive for the eye. Obviously this isn't your component's problem, but I was wondering if you've already solved this in any of your projects using scrollTo or otherwise. Thanks!

**Comment by naoufal** [comment]
Hey @mvayngrib, I've never toyed around with inverted views, but If you can add a code snippet to set that up I'd gladly take a look.

**Comment by naoufal** [comment]
Closing this while waiting for a code snippet.
